runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bower_components
  static_dir: dev/bower_components

- url: /partials
  static_dir: dev/partials

- url: /public
  static_dir: dev/public

- url: /.*
  static_files: dev/index.html
  upload: dev/index.html

- url: /
  static_files: dev/index.html
  upload: dev/index.html

skip_files:
- node_modules/
- bower_components/
- public/
- spec/
- scss/
- .git/
